kind: pipeline
type: docker
name: CI_Toxic_API

trigger:
  event:
    - push

steps:
  # - name: build
  #   image: node:16
  #   environment:
  #     MONGO_URL:
  #       from_secret: MONGO_URL
  #     PORT: 80
  #     HOST: localhost
  #   commands:
  #     - npm install
  #     - npx ts-node ./src/index.ts
  
  # - name: test
  #   image: node:16
  #   commands:
  #     - npm test
  #   depends_on: [build]

  - name: code-inspection_sonar
    image: node:16
    secrets: [ Login_Sonar_Toxi_API ]
    settings:
      sonar_project_key: Toxi_API
      project_sources: ./src
      sonar_host: https://codefirst.iut.uca.fr/sonar/
      sonar_token:
        from_secret: Login_Sonar_Toxi_API
    commands:
      - npm install -g sonarqube-scanner
      - sonar-scanner -Dsonar.projectKey=$${sonar_project_key} -Dsonar.login=$${sonar_token} -Dsonar.sources=$${project_sources} -Dsonar.host.url=$${sonar_host}
    # depends_on: [test]

# ---

# kind: pipeline
# type: docker
# name: CD_Toxic_API

# trigger:
#   branch:
#     - master
#   event:
#     - push


# steps:
#   - name: docker-build-and-push
#     image: plugins/docker
#     settings:
#        dockerfile: Dockerfile
#        context: .
#        registry: hub.codefirst.iut.uca.fr
#        repo: hub.codefirst.iut.uca.fr/nathan.verdier/toxic-api
#        username:
#          from_secret: 
#        password:
#          from_secret: 